#!/bin/bash
LENGTH=$#
for (( i=1 ; i<=$LENGTH ; i++ ))
do
gnome-terminal --title=Opened_Archive --geometry=100X25+300+150 -x bash -c '
CURRENTPATH=$(echo "$PWD")
cd ~/.local/share/nautilus/scripts/7-Zip
cd "$(cat dir7z)"
./7zzs l "$CURRENTPATH"/"$1"
#./7zzs l -ba "$CURRENTPATH"/"$1" | grep -oP "\S+$"
read abc
' bash "${!i}"
done
